server:
  port: ${SERVER_PORT:8090}

spring:
  sql:
    init:
      mode: always
  cloud:
    config:
      enabled: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:product-db}:${DB_PORT:5432}/${DB_NAME:product-db}}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:kafka:29092}
    topic:
      orchestrator: ${TOPIC_ORCHESTRATOR:orchestrator}
      product-validation-success: ${TOPIC_PRODUCT_VALIDATION_SUCCESS:product-validation-success}
      product-validation-fail: ${TOPIC_PRODUCT_VALIDATION_FAIL:product-validation-fail}
    consumer:
      group-id: ${CONSUMER_GROUP:product-validation-group}
      auto-offset-reset: latest

logging:
  level:
    org.apache.kafka: OFF
